Update writing_your_start-up_command.md
xwax/xwax.github.io pull request #13
Opened 2016-11-28 17:29 UTC by ximae

changed the folder scanning script so it can use folder names with spaces and some illegal characters. 
Also added a line so it checks that the files being made a crate are actually folders.

2016-11-28 17:33 UTC, lpil requested changes

2016-11-28 17:33 UTC, lpil commented on writing_your_start-up_command.md
> +(Fixed so it can take folders names with spaces and some illegal characters.)
No need for this remark I think :)

2016-11-28 17:33 UTC, lpil commented on writing_your_start-up_command.md
> +#!/bin/bash
```
#!/usr/bin/env bash
```

2016-11-28 17:33 UTC, lpil commented on writing_your_start-up_command.md
> +     PLAYLISTS="-l \"$P\" $PLAYLISTS"
Funky indentation here

2016-11-28 17:33 UTC, lpil commented on writing_your_start-up_command.md
> +gnome-terminal -e "xwax -a plughw:Audio4DJ,0,0 -a plughw:Audio4DJ,0,1 $(echo $PLAYLISTS)"
I'd prefer to avoid the gnome-terminal dep here.

2016-11-28 17:35 UTC, ximae commented on writing_your_start-up_command.md
> +gnome-terminal -e "xwax -a plughw:Audio4DJ,0,0 -a plughw:Audio4DJ,0,1 $(echo $PLAYLISTS)"
it needs to be launched through a new terminal or it wont work for some funky reason.

doesnt have to be gnome-terminal thugh, can be any.

2016-11-28 17:37 UTC, ximae commented on writing_your_start-up_command.md
> +(Fixed so it can take folders names with spaces and some illegal characters.)
ur right, first time i do a pull request didnt know i could leave comments of the changes afterwards. :D

2016-11-29 11:39 UTC, lpil commented on writing_your_start-up_command.md
> +gnome-terminal -e "xwax -a plughw:Audio4DJ,0,0 -a plughw:Audio4DJ,0,1 $(echo $PLAYLISTS)"
This should work without a new terminal. What happens?

2016-11-29 17:56 UTC, ximae commented on writing_your_start-up_command.md
> +gnome-terminal -e "xwax -a plughw:Audio4DJ,0,0 -a plughw:Audio4DJ,0,1 $(echo $PLAYLISTS)"
for some reason it doesnt take the double quotes in the path with a starightforward xwax command through the script ( thus not taking spaces in the foldername), but it does if manually add the double quotes to the path without the script or through a new terminal in the script.

its some odd behaviour i dont understand.

I opened a thread about it in the mailing list a week or two ago.  ill link you the message.

https://sourceforge.net/p/xwax/mailman/message/35504960/

just go ahead and try the script with a straightforward xwax command and then calling xwax through a new terminal.

2018-04-16 09:14 UTC, lpil commented
Thanks!

2018-04-16 09:14 UTC, lpil approved these changes

2018-04-16 09:14 UTC, merged

2018-04-16 09:15 UTC, lpil commented
Sorry about the incredible delay here, I did not see the updates